RobotLocomotion/director

src/python/ddapp/tabledemo.py
- also makes all the objects in the table demo be affordances where previously they were a mix of fieldcontainers and polydataitems
=> supporting multiple table environments with collision

src/matlab/test_rrt_valkyrie.m, src/python/ddapp/tabledemo.py
now the 5 scenes all have the same input information and can use collision free planning
=> more work on collision free planning

src/python/ddapp/drcargs.py, src/python/ddapp/startup.py
Adding --startup argument so that you can run other scripts at startup time in addition to startup.py, sharing the scope of startup.py
=> Adding a command line argument to execute other scripts at startup

README.rst
=> Citation info, closes #43

src/python/ddapp/footstepsdriver.py, src/python/ddapp/terraintask.py
The getContactPts function was modified to return left and right contact
points, but some code wasn't updated to handle the new data.
=> fix code using old style getContactPts()

src/python/CMakeLists.txt, src/python/ddapp/sceneloader.py, src/python/ddapp/thirdparty/conversions.py, src/python/ddapp/thirdparty/geometry_msgs_mock.py, src/python/ddapp/thirdparty/naming.py, src/python/ddapp/thirdparty/pysdf.py
Added option for loading affordances from a SDF file.
- Added a copy of pysdf from https://github.com/andreasBihlmaier/pysdf
- Removed dependency on ROS packages
- Bug fix: only first visual element and first collision element were loaded
- Created a loader class that parses the SDF and populates the scene with affordances based on collision objects defined in the file.
- Articulated structures (containing joints) are ignored.
- Only boxes and cylinders are loaded for now (because SCS can ontly use these shapes for contact detection).
=> Sdf loading vlad

src/python/ddapp/sceneloader.py
- Fixed SDF shape transformations (poses defined in model, link, collision, and visual now concatenate in correct order)
- Changed SDF affordance naming (dropped SDF prefix, zero length names, and collision/visual name suffix when link contains only one element of that type)
=> Fixed SDF shape transformations

src/python/ddapp/sceneloader.py, src/python/tests/testAffordanceItems.py
- Added SDF affordance unit test routine
- Simplified affordance naming
=> SDF affordance unit test

src/app/ddDrakeModel.cpp
previously, ddDrakeModel supported mitdrc/drake at revision
800a6744 from June 3rd 2015.  This change supports the latest
api of RobotLocomotion/drake master as of August 25th 2015.
=> update ddDrakeModel.cpp to support latest drake kinematics api

src/python/ddapp/drakevisualizer.py
Added the ability to apply different scaling for each dimension (before, only the first scale value was applied for all dimensions)
=> DrakeVisualizer: allow different scaling for each dimension

src/python/ddapp/continuouswalkingdemo.py, src/python/ddapp/ikplanner.py, src/python/ddapp/robotsystem.py, src/python/ddapp/tabledemo.py
Adds Neck pitch control with Val:
https://www.dropbox.com/s/2ika0icuqlzj7a6/2015-09-neck-control-val.ogv?dl=0
Also adds a few minor changes towards continuous walking in Val:
https://www.dropbox.com/s/oenqu0523ffvdul/2015-09-continuous-walking.ogv?dl=0
@patmarion @rdeits  all the footstep planning and perception code from Dec 2014 still works ;)
=> continuous walking with val

src/python/ddapp/startup.py
Commented out gridUpdater because it produces visual teleportation when using visualization-only execution
=> Solving grid teleportation problem 

src/python/ddapp/continuouswalkingdemo.py, src/python/ddapp/tabledemo.py, src/python/tests/testAffordanceItems.py
This removes the awkward dependency on having the test data repo in a particular place which was required by code in continuouswalking.py (ddapp)
**Merge [mit/drc](https://github.com/mitdrc/drc/pull/2131) pull request first.**
=> Updated paths to moved SDF files

src/python/ddapp/drakevisualizer.py
to support https://github.com/RobotLocomotion/drake/pull/1380
=> use new lcmtypes package

src/python/ddapp/continuouswalkingdemo.py, src/python/ddapp/playbackpanel.py, src/python/ddapp/startup.py, src/python/ddapp/tasks/robottasks.py, src/python/ddapp/teleoppanel.py
Continuous walking: robot walking over a series of planar up/down steps. For reliability reasons, we compute a new plan at each left foot contact using as starting status a double support constituted by the actual left foot pose and the predicted right foot pose. Task panel: we added a "continuous walking" button.
=> Sn continuous walking new

src/app/ddNavigation.ui, src/python/ddapp/continuouswalkingdemo.py, src/python/ddapp/navigationpanel.py, src/python/ddapp/startup.py
Continuous walking update (working). Task panel modified.
=> Continuous walking update (working)

src/python/ddapp/continuouswalkingdemo.py, src/python/ddapp/footstepsdriver.py
Added contact groups and test function for continuous walking.
=> Added contact groups and test function.

src/app/ddDrakeModel.cpp, src/app/ddDrakeModel.h, src/app/ddDrakeWrapper.cpp, src/matlab/IKServer.m, src/python/ddapp/startup.py, src/python/tests/testAtlasCommand.py, src/python/tests/testLoadUrdf.py, src/python/tests/testTeleopPanel.py
Pairs with https://github.com/mitdrc/drc/pull/2142/files
Currently this compiles but fails at run time. 
The major problem is that KinematicsCache separates the result of doKinematics() from the RBM.
I couldn't resolve how to pass the cache around with RBM object.
These two methods have problems:
URDFRigidBodyManipulatorVTK::getLinkToWorld
ddDrakeWrapper::resolveCenterOfPressure
=> update director to new drake

src/python/ddapp/footstepsdriver.py
Modification to #92. Updated y-values.
=> Updated feet contact points position according to SCS code.

src/python/ddapp/roboturdf.py, src/python/ddapp/viewbehaviors.py
previously flipping the hand frame between left and right just changed the color from yellow to green. that worked ok for atlas but doesn't work for valkyrie.
This code swaps the left/right meshes, rotates the frame by 180 and renames the objects and frames.
https://www.dropbox.com/s/wgdszyynxa0o3d1/2015-10-change-hands.mp4?dl=0
=> fix hand flips

src/python/ddapp/actionhandlers.py
Wee issue with the URL - fixed here
=> Fix URL for help

src/app/drakeVisualizerApp.cpp
...perhaps in the future this setup should be done in ddPythonManager
automatically
=> add missing call to pythonManager setSysArgv

src/python/ddapp/valvedemo.py
It works sort of with IHMC's SCS. There are a few outstanding issues, e.g. lots of infeasible plans because SCS goes beyond joint limits (issue reported) which kills planning and leads to infeasible constraints (the neck is wobbling as a result for example).
Issue List ValveDemo:
- sometimes 'wait for walking' throws an exception because it is already executing -- i.e. our state publisher isn't always working as intended (on the other hand, sometimes it works -- appears to be a timing thing)
- anklePitches over jointLimit (same as neckPitches -- reported to IHMC Bitbucket Issue tracker)
- the plans for the actual turning motion are invalid since it would kill its neck
It's currently in conflict but I'll fix that in due course and comment once it's ready to merge
=> Fix and format valvedemo

src/python/ddapp/continuouswalkingdemo.py, src/python/ddapp/plannerPublisher.py, src/python/ddapp/tabledemo.py
Related to
https://github.com/openhumanoids/main-distro/pull/2189
(one ihmc type remains)
=> remove includes of ipab types. these types are now in drc lcmtypes

src/python/ddapp/sceneloader.py, src/python/ddapp/startup.py, src/python/ddapp/tabledemo.py
Updated table demo to work with newly integrated final pose and rrt* planning.
=> Marco table demo

src/vtk/DRCFilters/vtkMapServerSource.cxx
=> adding field, tested on bot

src/python/director/viewbehaviors.py
- gives a reasonable view for when pelvis doesnt exist either
- fixes up the camera-at-head view, although it isn't actually used
=> fixes the camera reset. uses pelvis frame as Valkyrie doesnt have utorso

src/python/director/tabledemo.py
use lcmdrc instead of ipab which doesn't exist anymore
=> small fix to table demo

src/python/scripts/videoLogServer.py
Defualts back to original URL if the variable is not set.
=> Specify LCM community for the video logger via environment viariable.

src/python/scripts/videoLogServer.py
Reverts RobotLocomotion/director#141
=> Revert "Specify LCM community for the video logger via environment viariable."

src/app/ddTeleopPanel.ui, src/python/director/teleoppanel.py
This PR includes functions and controls to send foot poses to the IHMC controller allowing for single-foot stances.
=> ihmc single-foot support

src/app/ddTeleopPanel.ui
re-enable final pose planning controls
=> small fix to the GUI

src/python/director/ik.py, src/python/director/plannerPublisher.py, src/python/director/robotsystem.py, src/python/director/teleoppanel.py
This allows the adjusted joint limits to be passed onto EXOTica
=> Auto-extended joint limits get appended to the JSON planning requests

src/python/director/cameraview.py, src/python/director/startup.py
Reverts RobotLocomotion/director#154
=> Revert "Flip imageOverlay camera based on head frame"

src/python/director/cameraview.py, src/python/director/startup.py
Reverts RobotLocomotion/director#155
=> Revert "Revert "Flip imageOverlay camera based on head frame""

.gitignore, cmake/modules/FindDrake.cmake, src/app/ddDrakeModel.cpp, src/app/ddDrakeModel.h, src/app/ddDrakeWrapper.cpp
Builds with https://github.com/tkoolen/drake/tree/tk-dont-flatten-include-hierarchy.
(pull requested in https://github.com/RobotLocomotion/drake/pull/1612)
=> Bring drake up to date

src/python/director/actionhandlers.py, src/python/director/continuouswalkingdemo.py, src/python/director/ioUtils.py
Fixed continuous walking. Added save to .vtk option.
=> Sn continuous walking.

src/python/director/atlasdriver.py, src/python/director/continuouswalkingdemo.py, src/python/director/robotposegui.py, src/python/director/startup.py
https://github.com/openhumanoids/oh-distro/pull/32
=> extract atlas types

src/python/tests/testContinuousWalking.py, src/python/tests/testTeleopPanel.py
This addresses and resolves https://github.com/openhumanoids/oh-distro/issues/22
=> Fix unit tests for Valkyrie

src/app/ddScreenGrabber.ui
... to folders already created on a default ubuntu installation
=> suggestion to move the video and picture files

src/python/director/lcmoctomap.py, src/vtk/DRCFilters/CMakeLists.txt, src/vtk/DRCFilters/vtkOctomap.cxx, src/vtk/DRCFilters/vtkOctomap.h
Replacing:
https://github.com/RobotLocomotion/director/pull/177
This its possible to use octovis without modification.
But I have a few CMake issues. Could you suggest fixes?
- octovis doesn't install a pkgconfig file
- octovis requires something called QGLViewer - which is used only in one place - to draw an axes.
It is actually part of octomap and provides as FindQGLViewer.cmake
oh-distro/software/externals/octomap/octovis/src/extern/QGLViewer
I'll also PR some associated changes to open-humanoids if you want them
=> add color octree minimal

src/python/tests/CMakeLists.txt, src/python/tests/testEndEffectorIk.py
Computes a list of random samples of the arm joints, computes fk to
find end effector poses, then queries the ik engine for each pose.
This test should work for any robot with arm joints.  The test is
enabled to test the IRB140 and Atlas v5.
=> add testEndEffectorIk.py

src/app/ddPointCloudLCM.cpp
rgb color applied to color point cloud, float arrays seems to need to be rescaled
=> point cloud receiver can accept rgb and float arrays

src/python/director/valvedemo.py
the valve planner wanted simple=0, but the task properties had it
defined backward.
=> there was some inconsistency with turn mode 0 / 1 for simple / human

src/app/ddPointCloudLCM.cpp, src/app/ddPointCloudLCM.h, src/python/director/atlasdriver.py, src/python/director/continuouswalkingdemo.py, src/python/director/drivingplanner.py, src/python/director/jointcontrol.py, src/python/director/lcmframe.py, src/python/director/robotposegui.py, src/python/director/robotstate.py, src/python/director/roboturdf.py, src/python/director/segmentation.py, src/python/director/teleoppanel.py
because of the python, I cannot be sure i captured all type imports.
I tested with both SCS and MIT simulators - walking plans and reaching plans.
=> move to using bot_core types for many messages

src/python/director/startup.py
now produces this:
http://terminator.robots.inf.ed.ac.uk/public/shared/2016-03-16-contact_state_vis.mp4
Note that the Valkyrie F-T is inverted relative to Atlas
TODO: probably should switch to norm of force values for this esp as Val has a six axis F-T.
=> fix contact visualiser

src/python/director/teleoppanel.py
Sends JOINT_POSITION_GOAL message for [valkyrie_translator](https://github.com/openhumanoids/valkyrie_translator)
=> Neck Control Teleop Panel

src/app/ddMultisense.ui, src/python/director/multisensepanel.py, src/python/director/perception.py, src/python/director/startup.py, src/python/director/teleoppanel.py
- Removed neck pitch from Multisense Panel
- Added the neck pitch setting for Atlas to the Teleop Panel as well, changed Valkyrie's neck command channel
- Changed message type for DESIRED_NECK_ANGLES to joint_angles_t
=> Neck Control Updates

src/python/director/ikplanner.py
This reverts commit 9cf03acfd4e152a562e76a0cfe28d796c0a8fbbf.
fixes #235.
=> Revert "fixed ik missing pose variable error."

src/python/director/drakevisualizer.py, src/python/director/lcmUtils.py
This adds visualization of `planar_lidar_t` messages.
=> Visualizaton for planar lidar

src/python/director/segmentation.py
(still needs work, but this works well)
=> more fixes to use the new bounding box algorithm

src/app/ddTeleopPanel.ui, src/python/director/teleoppanel.py
being moved to val panel in oh-distro
=> remove-ihmc-buttons-from-teleop-panel

src/app/ddMotionPlanningPanel.ui, src/python/director/motionplanningpanel.py
- Added bi-hands reaching option
- Added walking plan fake execute option
- Some UI updates
=> Updated motion planning panel

src/python/director/segmentation.py
This uses the viewFrame position and the yaw from viewDirection as the head frame
=> Added a fix to table segmentation 

src/python/director/cameraview.py, src/python/director/startup.py
Thanks for the comments and fix in #212 @patmarion - this PR addresses these comments and cleans up the aspect ratio.
=> ImageWidget: Follow up to #212, #252

src/app/ddBotImageQueue.cpp, src/python/director/cameraview.py, src/python/director/startup.py
NOTE: kinect-lcm module is not necessary anymore, have depreciated support
for those lcm types
=> minimal changes to support openni pclouds with same code as multisense

README.rst, distro/travis/before_install.sh
homebrew/science doesn't include vtk5 anymore, so we have to work around it.
=> Fix OSX build by switching homebrew taps for vtk5

src/python/director/drcargs.py, src/python/director/footstepsdriver.py, src/python/director/roboturdf.py, src/python/director/teleoppanel.py
previously Valkyrie was referred to as V2 in some places, this has now gone away
=> remove support for really old valkyrie model (from 2014)

src/python/director/cameraview.py, src/python/director/depthimageprovider.py, src/python/director/perception.py, src/python/director/sensordatarequestpanel.py, src/python/director/startup.py, src/vtk/DRCFilters/CMakeLists.txt, src/vtk/DRCFilters/vtkMapServerSource.cxx
(towards breaking maps server off as a submodule)
paired oh-distro PR to follow
=> make maps server seperate from drc

src/python/director/coursemodel.py, src/python/director/doordemo.py, src/python/director/drilldemo.py, src/python/director/drivingplanner.py, src/python/director/egressplanner.py, src/python/director/handdriver.py, src/python/director/ikconstraintencoder.py, src/python/director/ikplanner.py, src/python/director/jointcontrol.py, src/python/director/lcmcollections.py, src/python/director/motionplanningpanel.py, src/python/director/plannerPublisher.py, src/python/director/roboturdf.py, src/python/director/sitstandplanner.py, src/python/director/startup.py, src/python/director/teleoppanel.py, src/python/director/valvedemo.py
Remove some unneeded imports and unused code.
Background:  I've been working on trying to get basic IK/teleop functionality working in Director using just the Drake tree and with the Python interface to Drake (instead of MATLAB).  This is some preliminary cleanup work which doesn't introduce any functional changes yet.
=> Cleanup some unused code/imports

src/python/director/cameracontrol.py, src/python/director/cameracontrolpanel.py, src/python/director/startup.py
previously could only follow ordinary objects e.g. affordances, polydata
demonstration:
https://www.dropbox.com/s/06riyifhrpxmer2/fly-around-1.mp4?dl=0
=> adding camera mode to follow/orbit/chase robot

src/python/director/drcargs.py, src/python/director/robotstate.py, src/python/director/roboturdf.py
Adds package paths and drcargs for dual arm husky
=> Add dual arm husky

src/vtk/DRCFilters/vtkFrameWidgetRepresentation.cxx
=> Fix a stack overrun issue.

src/python/director/cameracontrol.py, src/python/director/cameracontrolpanel.py, src/python/director/startup.py
remove dependencies from cameracontrol.py and fixes testCameraControl (so travis CI for linux should be green, hopefully)
=> Fix camera control panel

src/app/ddBotImageQueue.cpp, src/app/ddBotImageQueue.h, src/app/wrapped_methods_drc.txt, src/python/director/cameraview.py, src/python/director/segmentation.py
Added capability to display stereo cloud within a set depth. Default range is -1, which does not do any filtering.
=> Displaying stereo cloud with limited depth

src/python/director/kinectlcm.py, src/python/director/startup.py
Cleans up the Kinect LCM logic (which we still use alongside the OpenNIDepthImage) and renames the flag for it from useKuka to useKinect
=> Update Kinect LCM

src/python/director/roboturdf.py, src/python/director/startup.py
Thanks for your feedback Pat - please find the following PR to address #343 and be more graceful when certain parameters are not defined in the director_config
=> Warn when headLink undefined - be more graceful about director_config omissions

cmake/modules/FindDrake.cmake
it only exists in drake/master, but not the oh fork of drake.
this hack can be removed after the upgrade...
=> add drakeCommon as an optional library

src/app/ddDrakeModel.cpp, src/app/ddDrakeModel.h, src/app/ddDrakeWrapper.cpp
Reverts RobotLocomotion/director#354
=> Revert "Use RigidBodyTreed typedef "

src/python/director/applogic.py, src/python/director/startup.py
I hope this is okay given there's a major startup.py reshuffle in the works soon - this removes some of the panels on the right side bar if the corresponding flags are set to False.
=> Remove some panels if corresponding flags set to false

src/app/ddDrakeModel.cpp, src/app/ddDrakeModel.h, src/app/ddDrakeWrapper.cpp
Closes #367. 
RobotLocomotion/drake#4098 depends on this.
RobotLocomotion/drake#4098 passed CI (when pointing to this branch) and was LGTM'd be reviewers. Therefore this PR is ready for review. Could you please take a look @patmarion? Thanks!
=> Renames drake/multibody files from CamelCase to snake_case

src/python/CMakeLists.txt, src/python/director/assimp2vtk.py
this is some initial work for using the assimp (asset importer) 3rd party
library to load a variety of mesh file types, for example, collada dae
files.
=> add assimp2vtk module

src/python/director/perception.py, src/python/director/segmentation.py, src/vtk/DRCFilters/vtkMultisenseSource.cxx
wanted to get this one out of the way as its most hard coded.
=> rename some channels in the director for multisense

src/python/director/cameraview.py, src/python/director/continuouswalkingdemo.py, src/python/director/startup.py
=> minor channel renames

src/app/ddBotImageQueue.cpp, src/python/director/blackoutmonitor.py, src/python/director/cameraview.py, src/python/director/drivingplanner.py, src/python/director/startup.py, src/python/scripts/cameraViewer.py, src/python/tests/testDrawRobotLog.py, src/python/tests/testImageView.py
stereo and lidar point clouds and all the image view now work.
i think this is now done, baring some minor additional changes
=> more cccchanges to cccchannels

src/app/ddDrakeModel.cpp
Testing PR for RobotLocomotion/drake#4124
More work towards full RBT templatization.
=> Refactors RigidBody --> RigidBody<double>

src/python/director/robotsystem.py
Is this okay @patmarion? The alternative would be to have a startup script that sets the variable but this is neater.
=> Pick up planningMode from directorConfig if specified

src/python/director/robotsystem.py
Thanks for the fix-suggestion @patmarion, this worked :)
=> Fix affordance-copy, closes #391

src/app/ddPointCloudLCM.cpp, src/app/ddPointCloudLCM.h, src/app/wrapped_methods_drc.txt, src/python/director/perception.py, src/python/director/visualization.py, src/vtk/DRCFilters/vtkLidarSource.cxx, src/vtk/DRCFilters/vtkLidarSource.h
Reads from the configuration file for properties:
```
director_show = true;
sensor_name = "Sick Lidar";
intensity_range = [1, 400];
```
Multisense has been left as a default, as it has a specific config.
@mauricefallon
=> Reads Lidars from bot params

src/vtk/DRCFilters/CMakeLists.txt, src/vtk/DRCFilters/vtkLCMGLProp.cxx
Second attempt at #313 after #314 - this one checks if GLUT has previously been initialised and only initialises when it hasn't been.
=> Resolve #313 - initialisation of GLUT if it hasn't been previously done

src/vtk/DRCFilters/CMakeLists.txt, src/vtk/DRCFilters/vtkLCMGLProp.cxx
Reverts RobotLocomotion/director#426
=> Revert "Resolve #313 - initialisation of GLUT if it hasn't been previously done"

src/python/director/treeviewer.py
Simplify cached folder lookup a bit to avoid some bugs with stale folder caches. Also, eliminate `getItemByPath` which isn't actually necessary.
=> fix some issues with cached folders

src/python/director/treeviewer.py, src/python/director/visualization.py, src/python/tests/testTreeViewerInterface.py
=> Support drawing triads in the new TreeViewer

distro/travis/before_install.sh
This reverts commit 305c9274f4fbcec229a25493f3a5dade04a19cf7.
=> Revert "change homebrew taps for qt4 and vtk5"

src/python/CMakeLists.txt, src/python/director/treeviewer.py, src/python/director/viewerclient.py, src/python/tests/CMakeLists.txt, src/python/tests/testTreeViewerClient.py
~~patmarion this is just the beginning (and not ready to merge yet), but I wanted to open the PR so you can see what I'm doing here~~
(see the end of the file for some basic usage)
Todo:
=> first draft of python viewer client interface

src/python/director/treeviewer.py
once upon a time, those responses were lists, but not anymore.
=> fix a couple of typos

distro/package/make_linux_package.sh, distro/package/make_mac_package.sh
=> add commit hash to package names

src/python/director/pydrakeik.py, src/python/tests/testEndEffectorIk.py, src/python/tests/testPyDrakeIk.py, src/python/tests/testRobotPoseGui.py
see: https://github.com/RobotLocomotion/director/issues/467
=> add workaround for static tls issue

src/python/director/filterUtils.py, src/python/director/treeviewer.py, src/python/director/viewerclient.py
Fixes #478 
Fixes #477 
Fixes #479
=> Tree Viewer bug fixes

distro/superbuild/cmake/externals.cmake, distro/travis/before_install.sh
And remove the systemwide Eigen installs on Travis to make sure this actually works.
=> Make sure we build Eigen if we're not using the system version

src/python/director/treeviewer.py
Simple tweak to get multi-axis scaling working in the treeviewer.
=> Fix bug in treeviewer

distro/superbuild/cmake/externals.cmake
fixes mac build issue compiling pcl with c++11
=> update superbuild to use pcl 1.8.0

distro/travis/before_install.sh
This reverts commit 81a50ebbb0a8ee050bc31606475b4f091fa3cf40.
=> Revert "Revert "change homebrew taps for qt4 and vtk5""

src/python/director/drakevisualizer.py, src/python/director/ioUtils.py
This contains the changes to Director needed to resolve https://github.com/RobotLocomotion/drake/issues/5044.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/director/495)
=> Added support for obj/mtl to drake-visualizer.

CMakeLists.txt, cmake/modules/FindGLib2.cmake, cmake/modules/FindLCM.cmake, distro/superbuild/cmake/externals.cmake, src/app/CMakeLists.txt
PTAL @patmarion. FYI @stonier.
=> Support building and linking static libraries

src/python/director/drakevisualizer.py
the filename variable contains the resolved filename from geom.string_data
=> fix typo introduced by commit 0d378c7

distro/superbuild/cmake/externals.cmake
Fixes issue arising from #544. PTAL @patmarion.
=> Build position independent code

README.rst, distro/superbuild/cmake/externals.cmake, distro/travis/install_deps.sh
=> Update non-VTK external project versions

CMakeLists.txt, distro/superbuild/cmake/externals.cmake, src/app/CMakeLists.txt, src/app/ddBotImageQueue.cpp, src/app/ddPointCloudLCM.cpp, src/app/wrapped_methods_drc.txt, src/python/director/cameraview.py
- Enables build of bot_image_queue
- Disables kinectLCM driver
- Updates cameraview.py to be compatible with VTK \geq 6
Submitting so testing can spin up, but I'm happy to add a build option to allow this bit of code to only build when requested, since it has a more involved dependency list.
=> Update bot image queue for pointcloud visualization

distro/superbuild/cmake/externals.cmake, src/app/CMakeLists.txt
=> add cmake superbuild option to disable openni2 lcm driver

src/python/director/affordanceitems.py, src/python/director/plannerPublisher.py, src/python/director/sceneloader.py
This pull request adds support for loading mesh geometries from SDF files and also adds support for scaling of meshes.
Maybe this commit can also be cherry-picked onto master after merge?
cc: @wxmerkt
=> Adds support for mesh geometries to SDF scene loader

src/python/director/visualization.py
- consistent return value
- fix call to transformPolyData
- use transform if given
=> fix vis.addChildFrame function

src/python/director/viewerclient.py, src/python/tests/testTreeViewerClient.py
=> support PointCloud from the python tree viewer client

src/python/director/debugVis.py, src/python/director/visualization.py, src/python/tests/CMakeLists.txt, src/python/tests/testDebugVis.py, src/python/tests/testFrameTrace.py
makes drawing polylines more efficient and adds some tests
=> update drawing functions in DebugData and FrameTraceVisualizer

CMakeLists.txt, cmake/modules/FindLCM.cmake, distro/superbuild/cmake/externals.cmake, src/app/ddAppConfigure.h, src/app/ddQVTKWidgetView.cpp, src/app/vtkSimpleActorInteractor.h, src/app/vtkTDxInteractorStyleCallback.h, src/vtk/DRCFilters/vtkCollections.h, src/vtk/DRCFilters/vtkDRCFiltersModule.h, src/vtk/DRCFilters/vtkDepthImageUtils.h, src/vtk/DRCFilters/vtkFrameWidget.h, src/vtk/DRCFilters/vtkFrameWidgetRepresentation.h, src/vtk/DRCFilters/vtkGridSource.h, src/vtk/DRCFilters/vtkInteractorStyleTerrain2.h, src/vtk/DRCFilters/vtkLCMGLProp.h, src/vtk/DRCFilters/vtkLidarSource.h, src/vtk/DRCFilters/vtkMapServerSource.h, src/vtk/DRCFilters/vtkMultisenseSource.h, src/vtk/DRCFilters/vtkOctomap.h, src/vtk/DRCFilters/vtkPickCenteredInteractorStyle.h, src/vtk/DRCFilters/vtkPlaneSegmentation.h, src/vtk/DRCFilters/vtkRobustNormalEstimator.h, src/vtk/DRCFilters/vtkSurfaceFitter.h
Relates https://github.com/RobotLocomotion/spartan/issues/266. PTAL @patmarion.
=> Various compatibility updates

src/python/director/teleoppanel.py
=> remove unnecessary line causing bug

src/python/director/ioUtils.py
Adds ply reader to handle issues with ply files saved by pcl
=> add special ply file reader
