- src/python/tests/testDrakeVisualizer.py
need to use ConsoleApp.start() to get the testing mode behavior that
automatically triggers an exit after the application starts when the
--testing flag is given.
> fix testDrakeVisualizer.py to auto exit in testing mode

- src/python/ddapp/startup.py
Made syncing of hand joints more general. It checks whether the robot is any kind of Atlas and then keeps the old way (getRobotiqJoints) as it's underactuated and wouldnt return all hand joints from the hand model (getRobotiqJoints returns 1, 2, middle for each). Otherwise uses (all of) the hand model(s) to arrive at the hand joints, then filters out the base joints. 
I've compiled and started this up with v5, lwr, and val2. Then verified that ``teleopJointPropagator.jointIndices`` has indices. This is the case for v5 and lwr, and hence should work. Valkyrie doesnt seem to have hand models / factories defined yet.
cc @patmarion @mauricefallon
> Sync hand joints (more general)

- src/python/ddapp/roboturdf.py
- src/python/ddapp/segmentation.py
- src/python/ddapp/segmentationroutines.py
- src/python/ddapp/tabledemo.py
- src/python/ddapp/valvedemo.py
- src/python/ddapp/viewbehaviors.py
Supports human-like valve turning:
* defaults to original finals-style turning but can use human style turning
* verified that both modes work with atlas v5 in the mit simulator
* demo with val in scs:
https://www.dropbox.com/s/fkyw1t70dfoyttd/valve_turning_with_val.ogv?dl=0
Other:
* disabled the point cloud re-centering (from greg)
* fixed a hard coded 'head' string
> turn valve in a human manner

- src/app/CMakeLists.txt
- src/app/ddPointCloudLCM.cpp
- src/app/ddPointCloudLCM.h
- src/app/wrapped_methods_drc.txt
- src/python/CMakeLists.txt
- src/python/ddapp/pointcloudlcm.py
Supports using a generic PCL point cloud as a blob for data transmission in LCM and rendering in the designer
This function mirrors pc/conversions.hpp to convert between the lcmtype and an pcl point cloud:
pcl::fromLCMPointCloud2( message, *cloud);
which is defined in multisense_utils/conversions_lcm.hpp to decompress data
Alsod as a python widget based on the kinect widget.
Velodyne demo:
https://www.dropbox.com/s/ynjgj4sywrfb367/velodyne_in_viewer.mp4?dl=0
(Currently works with a specific XYZIR data type)
... drc PR to follow
> add generic pointcloud rendering

- src/matlab/test_rrt_atlas.m
- src/matlab/test_rrt_valkyrie.m
- src/matlab/test_rrt_valkyrie_v1.m
These scripts were directly generated from ddapp and test collision free reaching. The key thing is that they use the collisionFreePlanner class and runIKServer - so the tests help maintain integration.
To invoke:
matlab -nosplash -nodesktop -r "addpath(fullfile(getenv('DRC_BASE'),'software','build','matlab')); addpath_control; cd ([getenv('DRC_BASE') '/software/ddapp/src/matlab']); test_rrt_valkyrie() "
@patmarion : I would like to add these tests to the DRC build server. This would require adding
the ctest scripts from software/control to ddapp and making it play well with your python tests.
What do you think about doing this?
> adding scripts for rrt planning testing

- src/app/ddMainWindow.ui
- src/python/ddapp/playbackpanel.py
- src/python/ddapp/tabledemo.py
- src/python/ddapp/tasks/robottasks.py
- src/python/ddapp/tasks/taskmanagerwidget.py
- src/python/ddapp/valvedemo.py
- **Added shortcut F10 to open the task panel**, similar to F8, F9, and Ctrl+B - since we're finding ourselves opening the task panel a lot. Happy to change to another key, but F10 came in handy after F8, F9
- **Methods to jump in the task tree and continue** - in tabledemo used to repeat the spiel until there are no more objects that have been segmented (clusterObjects is empty). If there's a better way than pausing and continuing, please let me know :)
- **Fix for EXOTica planning when checking manip plan info**: EXOTica mirrors the 0 plan info for successful requests and 13 when constraints are not satisfied, but we also have negative return codes (this shouldn't conflict with Matlab planning - does it?)
- Minor changes that are flagged with the fixed base switch
> Updates to tabledemo and shared autonomy

- src/python/ddapp/ikconstraintencoder.py
- src/python/ddapp/thirdparty/numpyjsoncoder.py
- src/python/tests/testPlanConstraints.py
previously the output string encoding a numpy array was as follows:
"jointsUpperBound": {"__ndarray__": [0.0, 0.0, 0.0]},
@patmarion : is this a robust away of spotting an np.array and converting it to a list?
> clean up the output of the constraintencoder

- src/python/ddapp/tabledemo.py
- src/python/ddapp/tasks/robottasks.py
This series of commits allows to run the tabledemo even more autonomous and recognise whether the hand has grasped something - i.e. it does not require human verification of that the hand is closed and in fact has an item within its fingers.
- Added a new status topic ``GRASPING_STATE`` (boolean_t) that records whether an item has been grasped (``true``) or the hand was successfully opened (``false``)
- Implemented the above as a grasping task in robottasks -- waits (blocking) until a message is received or fails with a timeout (and then blocks further execution of the task tree)
- Added an addGrasping function for this
- Deactivated for humanoids and all others that dont have this message implemented yet
- Changed a few flags to check whether we are dealing with kukas rather than with a …
> Use hand grasping status in tabledemo (no more human acknowledgement required)

- distro/pods/drake-distro/install_prereqs.sh
This commit updates the install_prereqs.sh script to install vtk5
using MacPorts-2.3.4, on Mac OS X 10.10.
Signed-off-by: Elvis Dowson <elvis.dowson@gmail.com>
> Update installation pre-requisites when using MacPorts on Mac OS X 10.10.

- src/python/ddapp/valvedemo.py
@mauricefallon please sign off on this and confirm that this change is okay. We didn't see the ...-new.vtp and since it is working with the ihmc.vtp I changed the filename. If it is not the right move, please add the -new.vtp file to drc-testing-data -- thanks!
> Fix drc-testing-data filename

- src/python/ddapp/matlab.py
Changes the path from ``/tmp/matlab_commands.m`` to ``~/.drake-designer/matlab_commands.m``. It is hence user-specific and there won't be conflicts if drake-designer is used in multiple user accounts on the same machine without restarting.
Addresses https://github.com/openhumanoids/main-distro/issues/2177
> Make Matlab commands log file user specific

- src/python/ddapp/robotsystem.py
- src/python/ddapp/roboturdf.py
This is a working fix for #111, tested with Atlas v3, v4, v5, Valkyrie v1, v2, and the Kuka LWR. It sets the rendering mode to URDF Colors by default and overwrites it to "Texture" if given in the directorConfig
Goes along with https://github.com/openhumanoids/main-distro/pull/2196
> Fix for #111 - make URDF colors usable again

- src/python/ddapp/roboturdf.py
This fixes a bug @mauricefallon spotted that I introduced in #113 - toggling solid colors was broken when operating with textures. This PR allows for toggling between solid colors and textures, e.g. for the playback model
> URDF/Texture Solid Color Toggling Fix

- src/python/ddapp/startup.py
this evaluates a list of strings at the top of startup.py and disables the components e.g.:
this disables drake planning but will draw a robot and render sensor data:
"disableComponents" : ["useFootsteps","usePlanning","useFootContactVis","useCOPMonitor"]
> allow runtime config designer

- src/app/ddDrakeModel.cpp
- src/app/ddDrakeModel.h
- src/app/wrapped_methods_drake.txt
- src/python/director/robotsystem.py
- src/python/director/roboturdf.py
Pat, apologies for closing the issue without adding the color mode enum first (I wasnt aware of that fact and should have asked before closing).
Were you looking for something along the lines of this? This adds a enum for Color Mode and populates it with "Solid Color" per default, and then changes it according to a director config parameter to Textures or URDF Colors. I also changed "Texture" to "Textures" to have a common naming convention, cf. https://github.com/openhumanoids/main-distro/pull/2230.
This removes the Textures boolean property and replaces it with a Color Mode enum. Tested on v5, val2, lwr.
Addresses, and potentially closes #111
> Color Mode, per #111

- src/python/director/drcargs.py
Changing the command line argument from ```-val2``` to ```-val2s``` will load a set of simplified URDFs that use only basic shapes (coxes, spheres, and cylinders).
This uses openhumanoids/main-distro#2243
> Added command line argument to load Valkyrie with simplified models

- src/vtk/DRCFilters/vtkOctomap.cxx
Relates to https://github.com/openhumanoids/main-distro/issues/2067
Makes director compatible with newer octomap versions, tested with v1.7.0 (current release). This is the same patch as for the renderer_octomap.cpp in common_utils, which is also used in pronto.
cc: @patmarion & @mauricefallon
> Fix vtkDRCFilters for octomaps to add compatibility with newer octomap versions

- src/python/director/irisUtils.py
- src/python/director/irisdriver.py
On some systems we are getting the import error:
ImportError: dlopen: cannot load any more object with static TLS
which seems to be coming from the swig layer of iris.  The issue is
avoided by importing iris earlier.  It seems to be interacting in a
strange way with other modules loaded by director.
> import iris earlier to avoid import error

- src/python/director/cameraview.py
- src/python/director/startup.py
Reads the roll of the head frame and rotates the imageOverlay accordingly (to automatically account for the Valkyrie/Atlas Multisense rotation for instance). Next up is the same for the Camera View field.
> Flip imageOverlay camera based on head frame

- src/python/director/cameraview.py
- src/python/director/filterUtils.py
- src/python/director/startup.py
This flips the images directly in the ImageManager if the camera frame is rotated. Rotating at the lowest level is preferred compared to just rotating the camera when displaying it (and cascades through every use of the image). Tested with val2 and v5.
> Flip images in ImageManager if camera frame is rotated

- src/python/tests/CMakeLists.txt
Follow up from discussion https://github.com/RobotLocomotion/director/pull/173#issuecomment-178768268:
Proposal to add a check whether _extra_args_2 is set. If it is, then a second test is added with those arguments instead of the _extra_args. Note, it continues to assume Valkyrie by default and will only disable running the test on Valkyrie if _extra_args (without _2) is set/overwritten with the corresponding argument.
Pat, is there a way to (wildcard) loop over all _extra_args_{n} without having to set an integer and try increasing it in a for loop until it is not defined anymore? 
If this is OK, should we add all relevant robot tests to be run for both Valkyrie and Atlas v5?
> Proposal to add a second robot for unit tests

- src/python/director/roboturdf.py
Currently when the directorConfig does not have a headLink, director fails to fully load since cameraview is trying to load one. This will return None if there is no headLink in the director config.
> Work without headLink

- src/app/ddPointCloudLCM.cpp
- src/app/ddPointCloudLCM.h
- src/python/director/pointcloudlcm.py
Adds the capability to use a pointcloud_t type to transmit PC data over lcm to director
https://www.dropbox.com/s/wfi9gr65pxe1ycy/2016-02-00-vtk-lcm-director.m4v?dl=0
This type (which mirrors ROS pointcloud message) but is not intertwined with PCL.
I havent time right not to show how this can support sending arbitrary attributes in the 'channels' field (r,g,b, intensity, range, scan_id, echo, etc...). But this can support all the fields of a vtk polydata for example.
If you look at https://github.com/openhumanoids/oh-distro/pull/65 it provides the type and an example  which:
- loads a vtk file
- publishes to lcm at POINTCLOUD
- can be displayed and rendered in director
The type message:
https://github.com/oh-dev/oh-distro/blob/mf-use-pointcloud-type/software/drc_lcmtypes/lcmtypes/drc_point …
> use pointcloud_t type to transmit pointcloud data to director

- src/vtk/DRCFilters/vtkPlaneSegmentation.cxx
This allows more iterations when running plane fitting
with a perpendicularity constraint.  See:
https://github.com/openhumanoids/oh-distro-private/issues/2074#issuecomment-157876764
> set skipped iterations factor to 10

- src/python/director/cameraview.py
- src/python/director/startup.py
This PR includes two changes to the ImageOverlayManager and ImageWidget:
1. ImageOverlayManager now auto-detects the aspect ratio of the image to be displayed so that there is no more black borders at the top and bottom of the image
2. ImageWidget can be initialised hidden
3. ImageWidget is now the default for the toggle button in the user interface. The rationale behind this is that we often record videos with an image overlay on only to realise afterwards that it's a black spot instead of the video
4. The source of an ImageWidget can be changed without having to re-initialise the object
Pat, there are two remaining issues that I'd like to get your input on:
1. ImageWidget has unused padding left and right of the image, yet I could not find the right vtk command to get rid of it
2. …
> Image Widgets: auto-detect aspect ratio for ImageOverlayManager, make ImageWidget default

- src/python/director/drakevisualizer.py
> remove special fallback logic for importing drake lcmtypes

- src/python/director/propertyset.py
- src/python/tests/testPropertiesPanel.py
if you modify a property attribute inside a property changed callback
then the property panel rebuild event caused a crash.  By scheduling
the rebuild event to run after the callback completed the crash is
avoided.  The crash occurred because widgets are deleted during the
rebuild event.
> prevent crash by scheduling the property panel rebuild

- src/python/director/continuouswalkingdemo.py
- src/python/director/perception.py
- src/python/director/segmentation.py
- src/python/tests/testContinuousWalking.py
- stops using getOrientedBoundingBox (vtkAnnotateOBBs). reuses code from continuous walking block segmentation. in particular gives more reliable standing frame. still needs some improvement but works better than previous approach
edgePoint is no longer required for segmentTableEdge, but haven't changed it in argument.
Before (can actually be much worse):
After:
> use a minimum bounding box algorithm to recover the frame of a table

- src/python/director/drcargs.py
- src/python/director/ikplanner.py
- src/python/director/motionplanningpanel.py
- src/python/director/startup.py
@patmarion  Sorry for the late reply. The issue in #235 #236 is because pushToMatlab is used in a conflict way. It is used to indicate both 'push to matlab or not' and 'use matlab or exotica to solve IK'. I added a new variable to select the planning mode (for now, drake or exotica). The pushToMatlab var is now only used to indicate whether push things to matlab.
> Fix ik matlab communication

- src/python/director/midi.py
Mirroring what's there for findInputDevice
By the way, was there a specific reason not to use the python-midi package that can be installed via pip?
> Add findOutputDevice to midi.py

- src/python/director/robotviewbehaviors.py
i broke this when splitting view behaviors into robot view behaviors
> mark double click event as consumed after toggling footstep widget

- distro/pods/drake-distro/Makefile
This contributes to https://github.com/RobotLocomotion/drake/issues/2136.  
I'm sending you this PR because I can't think of a reason you would want `VERBOSE=1 make` to fail.  If there is a reason, we can instead change the Drake build to build the `all` target explicitly.
> Make "all" the default target in distro/pods/drake-distro.

- src/python/director/drakevisualizer.py
todo- re-use the loading code in actionhandlers.py.
currently this file can't be imported because of lcmtype
dependencies but this can be resolved soon.
> add vrml loading support to file menu of drake-visualizer

- src/python/director/perception.py
- src/vtk/DRCFilters/CMakeLists.txt
- src/vtk/DRCFilters/vtkLidarSource.cxx
- src/vtk/DRCFilters/vtkLidarSource.h
- src/vtk/DRCFilters/vtkMultisenseUtils.h
https://www.dropbox.com/s/ky5urvrvmv00hul/2016-06-01-director-general-lidar.m4v?dl=0
* Most of the new code is in python
* Many scanLines are rendered as opposed to a single Multisense sweep.
* Uses the same range-to-xyz conversion code as the multisense.
* adds vtkLidarSource.cxx which is very similar to vtkMultisenseSource.cxx. The only difference is some different parameters. This could be avoided, but perhaps future features will push these apart.
There's a few things to TODO:
- generalise to N lidars
- provide the channel names of the lidars to be used or directly read from config.
- Enable user interaction to copy item to a single static point cloud
> add general purpose lidar renderer

- src/python/director/debugVis.py
- src/python/director/drakevisualizer.py
@peteflorence thanks for the code!
This will be useful for, e.g. drawing inertial ellipsoids without resorting to LCMGL hacks. It will require an update to the list of enums in the corresponding Drake LCM type, but that change doesn't actually affect the LCM fingerprint so this should be fully backwards-compatible.
> support ellipsoids in debugVis and drakevisualizer

- README.rst
- distro/travis/before_install.sh
Note that I'm using the RobotLocomotion/director tap for the Readme (since that'll be the right thing going forward), but I'm using rdeits/director within Travis. That's because I've got exactly the version of the VTK5 recipe that matches the bottled version, so it will keep Travis happy until we make a new bottle.
> update readme for new vtk5 tap

- src/python/director/teleoppanel.py
Previously pressing the extending limits "No" button hid the Red button
and disabled the checker thereafter. This made it impossible to
subsequently plan when the robot was outside the limits.
this change merely closes the dialog. the user can still press 'Yes'
afterwards
> fixes issue with joint limit checker

- src/python/director/ikplanner.py
- src/python/director/startup.py
The back and neck joints are also zeroed. Don't move the arm joints.
this is required because the typical approach planNominal doesn't return
the robot to a known configuration
> move the pelvis above the mid point of the feet with zero roll and pitch

- src/python/director/robotviewbehaviors.py
The translate does not seep to work because selectedGroundPoint and footFrame are in different coordinate frames.
> Fix widget footstep goal computation

- src/python/CMakeLists.txt
- src/python/director/continuouswalkingdemo.py
- src/python/director/motionplanningpanel.py
- src/python/director/plannerPublisher.py
- src/python/director/planningutils.py
- src/python/director/startup.py
- src/python/director/teleoppanel.py
Follow up to our lunch discussion with @mauricefallon @yimingyanged @VladimirIvan 
1. Adds ``planningUtils`` in order to assemble methods that are commonly used in motion planning and currently fragmented across multiple files
2. ``planningUtils`` provides a ``getPlanningStartPose()`` method that by default clamps the ``startPose`` of planning problems to the joint limits - thus averting invalid motion plans (that e.g. trip up IHMC's controller)
3. Replaced all uses of manually getting the poses in the teleop and motion planning panels with the new ``getPlanningStartPose`` method
@mauricefallon @yimingyanged would you please have a look over this?
cc: @MarcoCar FYI
**ToDo:**
- this would mean extending the field 'disableComponents' which can switch off components. There should be both a …
> Clamp planning start pose to joint limits

- src/python/tests/testContinuousWalking.py
- src/python/tests/testContinuousWalking_staircase.py
- src/python/tests/testTeleopPanel.py
Now that a build server is back up, it became clear that https://github.com/RobotLocomotion/director/pull/295 broke some of our unit tests, cf. [build server failures](http://kobol.csail.mit.edu/cd/viewTest.php?onlyfailed&buildid=23686).
This PR fixes some of them. Additionally, the catkin workspace is now being built on the server a well which should take care of a further few.
> Fix unit tests

- distro/superbuild/cmake/externals.cmake
For reference: https://github.com/RobotLocomotion/drake/issues/3703#issuecomment-252459041
> Updated from-source-vtk5 to point to an updated clone that defines GLX_GLXEXT_LEGACY.

- src/python/director/drakevisualizer.py
fixes #317 
This implements an initial draft of point cloud support in the `drake-visualizer` interface. I expect that it may need to evolve a bit to support all of our use cases, but I think this is a good start. 
The interface I'm proposing is as follows:
To draw a point cloud, the user sends a message of type `bot_core::pointcloud_t` on the channel `DRAKE_POINTCLOUD_<pointcloud name>`, where `<pointcloud name>` is some unique name to identify this particular point cloud. The format of the message is:
* `n_points`: number of points in the pointcloud
* `points`: `n_points` x 3 array of points in world x, y, z coordinates
* `n_channels`: number of additional data channels (such as desired color, see below)
* `channel_names`: `n_channels` array of strings naming particular data channels.
* …
> support point clouds in the drake visualizer interface

- src/python/director/drakevisualizer.py
Currently, a DRAKE_VIEWER_LOAD_ROBOT message deletes the entire drake visualizer folder in the Director object model, which also deletes all point clouds currently being displayed. This change prevents point clouds from being deleted. 
Alternatively, instead of accepting this change, we can decide that the current behavior is actually correct. I'm open to discussion. Should drawing a new robot clear the pointclouds?
> don't clear pointclouds on load_robot

- distro/superbuild/cmake/externals.cmake
I tested on this on Ubuntu 16.04 with ROS Kinetic (which has VTK6) and it worked -- the error was printed during the configure stage. I also tested it on Ubuntu 14.04 with ROS Indigo and Director was able to compile using the system VTK.
Resolves #311.
> Added logic to fail fast if user wants to use system VTK but version 5 is not available.

- src/python/director/perception.py
- src/vtk/DRCFilters/vtkLidarSource.cxx
- src/vtk/DRCFilters/vtkLidarSource.h
- src/vtk/DRCFilters/vtkMapServerSource.cxx
- src/vtk/DRCFilters/vtkMapServerSource.h
- src/vtk/DRCFilters/vtkMultisenseSource.cxx
- src/vtk/DRCFilters/vtkMultisenseSource.h
- src/vtk/DRCFilters/vtkMultisenseUtils.h
for example you can choose to only show lidar 1m below and 2m above the body frame. especially useful for mobile robots where trees and ceilings are a pain as you are usually only interested in the above
demo shows the previous case (with the trees in the way) and then the control dials were added to show only the lidar around the robot's height:
https://www.dropbox.com/s/vghhtrwi7iojuzo/2016-10-lidar_height_control.mp4?dl=0
To be honest I was surprised at the sheer number of changes needed to add this feature
> adds relative height filtering for lidar

- src/app/ddDrakeModel.cpp
- src/app/ddDrakeModel.h
- src/app/ddDrakeModelOH.cpp
- src/app/ddDrakeWrapper.cpp
This PR depends on Drake's PR in RobotLocomotion/drake#3969. That PR must be merged before this one.
This PR simply replaces all the occurrences of `RigidBodyTree` with `RigidBodyTreed`. Per RobotLocomotion/drake#3969, `RigidBodyTreed` simply is a typedef to `RigidBodyTree`.
When RobotLocomotion/drake#3940 the typedef, from Drake's side, will be updated to `RigidBodyTree<double>`.
> Use RigidBodyTreed typedef 

- src/python/director/startup.py
Currently when useKinect is set it automatically starts the listener and update which is heavy on the CPU. Deactivate by default.
Merging as this is minor and only used locally for two projects (and we've changed the default behavior with a previous PR a few days ago)
> Deactivate auto-start of Kinect when useKinect is activated

- src/python/director/ikplanner.py
- src/python/director/startup.py
- src/python/director/teleoppanel.py
- Only create back constraints if the robot has back joints specified in the director config
- Add flag to be able to set ``ikPlanner.robotNoFeet`` from director config via the startup.py component enable/disable
@patmarion would you mind having a look at this whether this is okay/as intended? Using it here to fix teleop planning for a mobile/floating base non-humanoid robot. Tested with val and lwr to verify those still work
> Fix default constraint creation for mobile, fixed, humanoid robots

- src/python/director/drakevisualizer.py
The callbacks associated with child frames do not scale well for greater
than a few hundred instances, and there are now users of drake visualizer
that are generating hundreds of links.
Perhaps in the future I'll optimize the frame callbacks, but for now I am
just removing child frames from the implementation.
> remove usage of child frame objects for links in drake-visualizer

- src/python/director/drakevisualizer.py
this code was recently modified to optimize the viewer for scenes with
many links.  but the camera follower needs to use child frames.
fixes #378.
> if a child frame exists then use it

- src/python/director/drakevisualizer.py
Fixes #389 
drakevisualizer now listens to `DRAKE_VIEWER_ADD_ROBOT` ~~and DRAKE_VIEWER_REMOVE_ROBOT~~. `ADD_ROBOT` has the same message type as the existing `LOAD_ROBOT`, but does not clear existing robots (unless an existing robot has the same robot ID number as the robot being added). ~~REMOVE_ROBOT just includes a single robot ID number to delete, or -1 to delete all robots.~~
~~Note: I am abusing the LCM `utime_t` here as the message type for `REMOVE_ROBOT`, in order to avoid creating a branch new LCM type just to send an integer. This feels gross, but I think I'm OK with it~~
> Support adding and removing robots in drakevisualizer

- src/app/ddDrakeModel.cpp
In Drake, I'm working on establishing a layering rule where the URDF and SDF parsers depend on `RigidBodyTree` and not vice versa. For background and motivation, see https://github.com/RobotLocomotion/drake/pull/4317#issuecomment-264149254. This PR modifies Director to conform to this layering design.
> Updated URDFRigidBodyTreeVTK to Call URDF Parser Directly.

- src/app/ddDrakeModel.cpp
Constructor for `KinematicsCache` from a list of bodies will no longer be available to break the dependency of `KinematicsCache` on `RigidBody`. Per RobotLocomotion/drake#4378, `RigidBodyTree` manages the creation of a proper cache. 
This PR updates director to use that new API.
> Updates to use RBT::CreateKinematicsCache()

- src/app/ddDrakeModel.cpp
- src/python/director/pydrakeik.py
In https://github.com/RobotLocomotion/drake/pull/4363, @jwnimmer-tri recommended that we switch from using a `PackageMap` of type `std::map<string, string>` to a dedicated class.
See: https://reviewable.io/reviews/RobotLocomotion/drake/4363#-KYZFibpGHR_kRG_OCOm
This PR updates Director to use this new `PackageMap`. It should not be merged until after https://github.com/RobotLocomotion/drake/pull/4363 is merged.
> Updates Director to use Drake's new PackageMap class.

- distro/travis/copy_files.sh
it doesn't exist by default on the docker ubuntu image
> in copy_files.sh, ensure that ~/.ssh exists

- distro/docker/Dockerfile
removes code that sets env for gcc 4.9
> in Dockerfile use default compiler

- src/python/tests/CMakeLists.txt
Add logic to wrap tests with `xvfb-run` when necessary, so that tests can be run on headless systems (e.g. for CI).
> Use VFB for tests

- distro/travis/before_install.sh
this is a temporarily fix until a new qt4 formula with bottles is found,
or director migrates to qt5.
> use a fixed revision of homebrew to maintain qt4 support

- src/python/tests/CMakeLists.txt
Add parameter to `xvfb-run` to "try to get a free server". This is necessary to avoid collisions when running the tests in batch that lead to spurious failures.
> Avoid XVFB collisions

- src/python/director/ikplanner.py
Added an option to compute home nominal plans without moving the arms.
Such function used to exist in the past.
Fixed indentation and spaces.
> Added option to keep arm pose when planning nominal pose

- src/python/tests/CMakeLists.txt
Mark tests using `xvfb-run` as depending on a shared resource. This will prevent trying to create many VFB's in parallel, which can result in `xvfb-run` being unable to allocate a display.
> Disable parallel XVFB tests

- src/python/director/sceneloader.py
- src/python/director/thirdparty/pysdf.py
This PR adds parsing of color to pysdf and consequently to sceneloader, i.e. loaded SDF worlds aren't limited to grey boxes anymore.
The only supported version is by adding a material tag with a RGBA color. The alpha channel is not used though:
```xml
<material name="blue">
<color rgba="0 0 .8 1" />
</material>
```
> Add color to SDF Sceneloader

- src/python/CMakeLists.txt
- src/python/director/drakevisualizer.py
- src/python/director/drakevisualizerapp.py
- src/python/director/mainwindowapp.py
- src/python/director/treeviewer.py
- src/python/tests/CMakeLists.txt
- src/python/tests/testTreeViewerInterface.py
* changes all internal variants of drakevisualizer2 and viewer2 to treeviewer
* changes LCM channels to `DRAKE_TREE_VIEWER_{REQUEST|RESPONSE}`
* enables both the (old) drakevisualizer and (new) treeviewer in the drake-visualizer app, since they use separate LCM channels
> rename drakevisualizer2 to treeviewer

- src/python/tests/testTreeViewerInterface.py
This code is copied over from the drake interface test. It could also be refactored out, but I'm somewhat more inclined towards code reuse within tests than I would otherwise be.
> launch viewer window in tree viewer test

- src/app/ddBotImageQueue.cpp
- src/python/director/imageviewapp.py
the multisense lcm driver sets pixel type to GRAY when it uses uint16
and not GRAY16, so guess the pixelformat from the row_stride.
also adds disparity flag to imageviewapp.
todo: shouldn't need to specify the image type, should display any image
type
> support pixelformat GRAY from multisense lcm driver

- src/python/director/treeviewer.py
- src/python/director/viewerclient.py
- src/python/tests/testTreeViewerClient.py
- src/python/tests/testTreeViewerInterface.py
Deprecates the old `load()` and `draw()` commands, so they'll still work for now but will issue warnings. 
Fixes #452 
Also creates fewer unnecessary polyDataItems, which means that copying properties from one polyDataItem to another is no longer necessary, which fixes #451
> rename load -> setgeometry and draw -> settransform and fix polyDataItem properties

- src/python/director/treeviewer.py
Fixes an ultimately harmless but annoying error message:
```
ERROR: In /tmp/vtk5-20160602-81757-1afa8z2/VTK5.10.1/Common/vtkPoints.cxx, line 172
vtkPoints (0x7f8ed5054fd0): Number of components is different...can't set data
```
when trying to construct a mesh with zero points.
> don't try to generate empty meshes

- src/python/director/debugVis.py
`debugData.addCapsule` and `.addEllipsoid` didn't actually pass the color attribute down to the underlying polydata. This wasn't observed before because we were previously using the polyDataItem's color prior to #453
> fix missing color attribute for some geometry types

- src/python/director/planplayback.py
- src/python/director/pydrakeik.py
The interpolate.pchip is just an alias of PchipInterpolator and does not
exist in older versions of scipy.
> call interpolate.PchipInterpolator instead of interpolate.pchip alias

- src/python/director/treeviewer.py
- src/python/director/viewerclient.py
- src/python/tests/testTreeViewerInterface.py
cc @patmarion 
Clients should send requests on `DIRECTOR_TREE_VIEWER_REQUEST_<foo>` and listen on `DIRECTOR_TREE_VIEWER_RESPONSE_<foo>`. The old behavior will still work, but raises a deprecation warning. 
This also updates `viewerclient.py` to follow the new protocol (using a unique temporary filename as its client ID). `testTreeViewerInterface.py`, however, is still testing the deprecated protocol (for now).
> Add a unique client_id to the channel name in the treeviewer protocol

- src/python/director/debugVis.py
- src/python/director/treeviewer.py
- src/python/director/viewerclient.py
- src/python/tests/CMakeLists.txt
- src/python/tests/testTreeViewerPolyLine.py
Fixes #473 
Adds the "line" type to the JSON interface which can consist of an arbitrary number of points, plus options to determine whether to close the loop and whether to draw arrow heads at the start or end of the line. 
Also, fixes the arrow head length calculation, so arrows now end with their point exactly at the target point, rather than 0.5 * headRadius away.
> Support lines and arrows in the tree viewer interface

- src/python/director/segmentation.py
- src/python/director/timercallback.py
Adds two new properties to DisparityPointCloudItem to allow data to expire and be automatically removed if no new messages have been received for a given timeout/expiration time.
> Add option to automatically remove stale disparity data

- distro/superbuild/cmake/externals.cmake
- src/app/CMakeLists.txt
- src/app/QVTKOpenGLInit.cpp
- src/app/QVTKOpenGLInit.h
- src/app/consoleApp.cpp
- src/app/ddQVTKOpenGLWidgetConfigure.h.in
- src/app/ddQVTKWidgetView.cpp
- src/app/ddQVTKWidgetView.h
- src/app/drakeVisualizerApp.cpp
- src/app/main.cpp
- src/app/wrapped_methods.txt
Supersedes #523.
Implements suggestions from https://github.com/RobotLocomotion/director/pull/523#issuecomment-309072144
> VTK 8.0 and QVTKOpenGLWidget integration

- distro/package/make_mac_package.sh
fixes #532 (I think). I can't actually test this without a case-sensitive file system, but I think this is the right fix.
> fix symlink capitalization in mac package

- distro/travis/install_deps.sh
this is a temporary fix to workaround a recent change in homebrew Python that caused the build to fail.
> use fixed revision of homebrew/core formula 

- src/app/ddQVTKWidgetView.cpp
The render window size is updated when a QResizeEvent happen. At construction
time, the render window size is set to (0,0). This can cause problem if one
requests the size of the render window (e.g. to compute its aspect ratio)
before a QResizeEvent happen.
> Initialize render window size in ddQVTKWidgetView constructor

- src/python/director/lcmlogplayer.py
- src/python/director/qtutils.py
This is a basic change to (a) enable playback from a non-zero start value and (b) show the slider animated during playback.
Motivation:
I am using `sim_playback` to record a simulation with different actors enabled / disabled per scene. If it starts from 0.0, then it will call the `LOAD` messages, which will cause the visibilities to all be turned back on.
(Animation was just so I can see where I was at.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/director/522)
> Add simple slider animation when playing. Enable playback from non-zero.

- src/app/ddLCMSubscriber.h
Previously the `mTimer` wasn't being started. If you then called `setSpeedLimit(60)` then the notification would never get passed up to `python` due to the fact that `mTimer.elapsed()` was always equal to zero. So we would get stuck [here](https://github.com/RobotLocomotion/director/blob/master/src/app/ddLCMSubscriber.h#L162). 
I think this bug has been here all along. Probably what happened is that the default behavior changed when we upgraded the Qt version (or it's simply undefined and behaves strangely on 16.04). Anyways I think this PR fixes the issue.
@patmarion
> start the mTimer during initialization of ddLCMSubscriber

- src/app/ddDrakeWrapper.cpp
This change happened in drake commit c40f4a04d211934d553e99f0e5a164f4b0f806c5.
The commit message states:
Move convex_hull from /util to /systems/robotInterfaces
It's only used from within controllers, and shouldn't be used elsewhere.
We mark it private, since it's only used from .cc files, also.
> In drake, convexHull.h was renamed to convex_hull.h and moved

- distro/superbuild/cmake/externals.cmake
This pulls a version of QtPropertyBrowser where extra
compiler flags like -march-native have been removed.
See:
https://github.com/RobotLocomotion/drake/issues/7740
> update sha1 of QtPropertyBrowser used for qt5 build

- distro/superbuild/cmake/externals.cmake
(Remove references to the C libbot LCM types.)
> Point cv-utils to a version compatible with libbot as installed by modern Drake

- src/app/ddDrakeModel.cpp
See https://github.com/robotlocomotion/drake/pull/8085 for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/director/595)
> Fix deprecated usages of RigidBodyTree::bodies

- src/python/director/drakevisualizer.py
This makes it possible for future versions of drake to completely remove `drake-visualizer`'s dependency on pydrake. It should be fully backwards compatible (since it just prevents package lookup from crashing if pydrake is not found).
> Make pydrake optional in drakevisualizer.py

- distro/superbuild/cmake/externals.cmake
This allows compilation to succeed with newer versions of VTK which
remove some deprecated functions.
> Update to pcl 1.8.1 and newer PointCloudLibraryPlugin

- src/python/director/pydrakeik.py
We're interested in updating Spartan to Drake master, which exposed some package names that have gone out of date in the Pydrake IK stuff.
I'm not familiar with what the intended supported Drake versions are any more, so I'm not very confident this handles compatibility very well, though I tried to make the RigidBodyTreeCompatOld still work (though I don't have a way to test it).
We're happy with this living on a branch on this repo if that's easier!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/director/616)
> Fix pydrakeik for modern drake compatibility
